shutdown /s /m \\Maven00 /t 0
shutdown /s /m \\Maven01 /t 0
shutdown /s /m \\Maven02 /t 0
shutdown /s /m \\Maven03 /t 0
shutdown /s /m \\Maven04 /t 0
shutdown /s /m \\Maven05 /t 0
shutdown /s /m \\Maven06 /t 0
shutdown /s /m \\Maven07 /t 0
shutdown /s /m \\Maven09 /t 0
shutdown /s /m \\Maven10 /t 0
shutdown /s /m \\Maven11 /t 0
shutdown /s /m \\Maven13 /t 0
shutdown /s /m \\stanislaus /t 0
shutdown /s /m \\Yuba /t 0
shutdown /s /m \\QLDC2 /t 0
shutdown /s /m \\PlanetExpress /t 0
shutdown /s /m \\Data /t 0
shutdown /s /m \\data2 /t 0
shutdown /s /m \\hvmanager /t 0
shutdown /s /m \\prod-ws-ha /t 0
shutdown /s /m \\prod-ws-hb /t 0
shutdown /s /m \\Napa /t 0
shutdown /s /m \\enterprise00 /t 0
shutdown /s /m \\enterprise01 /t 0
shutdown /s /m \\enterprise02 /t 0
shutdown /s /m \\enterprise03 /t 0
shutdown /s /m \\enterprise04 /t 0
shutdown /s /m \\enterprise05 /t 0
shutdown /s /m \\enterprise06 /t 0
shutdown /s /m \\enterprise07 /t 0
shutdown /s /m \\enterprise08 /t 0
shutdown /s /m \\enterprise09 /t 0
shutdown /s /m \\enterprise10 /t 0
shutdown /s /m \\enterprise11 /t 0
shutdown /s /m \\enterprise12 /t 0
shutdown /s /m \\enterprise13 /t 0
shutdown /s /m \\enterprise14 /t 0
shutdown /s /m \\enterprise15 /t 0
shutdown /s /m \\enterprise16 /t 0
shutdown /s /m \\discovery00 /t 0
shutdown /s /m \\discovery01 /t 0
shutdown /s /m \\discovery02 /t 0
shutdown /s /m \\discovery03 /t 0
shutdown /s /m \\discovery04 /t 0
shutdown /s /m \\discovery05 /t 0
shutdown /s /m \\discovery06 /t 0
shutdown /s /m \\discovery07 /t 0
shutdown /s /m \\discovery08 /t 0
shutdown /s /m \\discovery09 /t 0
shutdown /s /m \\discovery10 /t 0
shutdown /s /m \\discovery11 /t 0
shutdown /s /m \\discovery12 /t 0
shutdown /s /m \\curiosity00 /t 0
